### ISSUE TITLE
Suggestion - Scrolling and Integration

### ISSUE THREAD

**Issue by melanchol69** [Tavyza/TherOS#7]
When I used the file manager, I was finding that many files were been made beyond the screen, it would be great to be able to scroll through these files so people can access all files in the system without using the terminal.
Also with the program installer, maybe including the floppy disk installation in the main option to install programs both from the internet and from local sources.

By the way, the last version I used was TherOS 1.0.3

**Comment by Tavyza** [comment]
Alright, i will work on this

**Comment by Tavyza** [comment]
Added in 1.1.3
